default:
  random_seed: 27

datamodule:
  data_dir: "/media/youngwon/Neo/NeoChoi/Dataset"
  batch_size: 144
  
  resize32: False
  scaling: False #True: [-1,1], False: [0,1]

model:
  latent_dim: 2

optim:
  lr: 0.001

train:
  logger_path: "./logger"
  devices: 1
  max_epochs: 300