default:
  random_seed: 27

datamodule:
  data_dir: "/media/youngwon/Neo/NeoChoi/Dataset"
  batch_size: 256

  resize32: False
  scaling: False

model:
  latent_dim: 2

optim:
  lr: 0.001

train:
  logger_path: "./logger"
  devices: 1
  max_epochs: 100