default:
  random_seed: 27

datamodule:
  data_dir: "/media/youngwon/Neo/NeoChoi/Dataset"
  batch_size: 256

  resize32: True
  scaling: True

model:
  latent_dim: 100

optim:
  lr: 0.0002
  b1: 0.5
  b2: 0.999

train:
  logger_path: "./logger"
  devices: 1
  max_epochs: 100